FROM ubuntu
MAINTAINER icoz

RUN apt-get update && apt-get install -y syslog-ng-core syslog-ng-mod-mongodb && apt-get clean


ADD ./syslog_docker.conf /etc/syslog.conf
RUN sed 's/PYSYMO_HOST/{{host}}/' -i /etc/syslog.conf
RUN sed 's/PYSYMO_PORT/{{port}}/' -i /etc/syslog.conf
RUN sed 's/PYSYMO_DB/{{db}}/' -i /etc/syslog.conf


CMD [ "/usr/sbin/syslog-ng",  "-f", "/etc/syslog.conf", "--no-caps", "-e", "-F" ]

